name: CI
on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: changeme
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fwilhe2/bump-version@wip
      id: v
    - run: echo ${{ steps.v.outputs.newVersion }}
